version: '3.7'

networks:
  kong-fc:
    external: true

services:
  jurishand:
    build: 
      context: .
      dockerfile: .docker/dockerfiles/Dockerfile
    container_name: jurishand
    volumes:
      - .:/usr/jurishand/app
    entrypoint: sh ./.docker/entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/api/articles"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:root@db:3306/jurishand
      PORT: 3000
    tty: true
    restart: on-failure
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - kong-fc
    extra_hosts:
      - host.docker.internal:host-gateway 
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: jurishand-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jurishand
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kong-fc
    extra_hosts:
      - host.docker.internal:host-gateway 