version: '3.7'

networks:
  kong-fc:
    external: true

services:
  jurishand:
    build: 
      context: .
      dockerfile: .docker/dockerfiles/Dockerfile
    container_name: jurishand
    volumes:
      - .:/usr/jurishand/app
    environment:
      NODE_ENV: development
    tty: true
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - kong-fc
    extra_hosts:
      - host.docker.internal:host-gateway 